name: chatbot-rest
services:
    webapp:
        image: demo-chatbot:local
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "9090:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=local
            - APPLICATION_PDF=pdf
        cpus: 2
        mem_limit: 4096m