#FROM nvidia/cuda:12.5.1-base-ubuntu22.04
FROM ghcr.io/ggerganov/llama.cpp:full-cuda
LABEL authors="leedg17"

RUN apt update  \
    && apt install -y vim

## ubuntu
RUN addgroup appgroup && adduser appuser && adduser appuser appgroup
### alpine
##RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /home/appuser
#
#RUN mkdir -p safetensors llama.cpp
#RUN git clone https://github.com/ggerganov/llama.cpp
#COPY llama-cpp-b4435-bin-ubuntu-x64.zip llama.cpp.zip
#RUN unzip llama.cpp.zip -d llama.cpp
ENV PATH="$PATH:/app"
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/app"

ENTRYPOINT ["top", "-b"]