FROM alpine:3.20 AS prePhase

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /home/appuser

RUN mkdir ollama
COPY ollama-0.5.1-linux-amd64.tgz ollama-linux-amd64.tgz
RUN tar xvf ollama-linux-amd64.tgz -C ollama


FROM nvidia/cuda:12.5.1-runtime-ubuntu22.04
LABEL authors="leedg17"

RUN apt update  \
    && apt install -y vim

## ubuntu
RUN addgroup appgroup && adduser appuser && adduser appuser appgroup
### alpine
##RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /home/appuser
ENV PATH="$PATH:/home/appuser/ollama/bin"
RUN mkdir -p .ollama/models ollama

COPY --from=prePhase --chown=appuser /home/appuser/ollama ollama

ENV OLLAMA_HOST=0.0.0.0
CMD ["serve"]
ENTRYPOINT ["ollama"]