#FROM nvidia/cuda:12.5.1-base-ubuntu22.04
FROM nvcr.io/nvidia/pytorch:24.04-py3
LABEL authors="leedg17"
LABEL email="angry07@naver.com"

#RUN apt update  \
#    && apt install -y vim python3 python3-pip

RUN python -m pip install --upgrade pip
RUN pip install torch==2.5.1 torchvision torchao
RUN pip install torchtune

## ubuntu
RUN addgroup appgroup && adduser appuser && adduser appuser appgroup
### alpine
##RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /home/appuser

ENTRYPOINT ["watch", "-n", "10", "nvidia-smi"]
