#FROM nvidia/cuda:12.5.1-base-ubuntu22.04
FROM nvcr.io/nvidia/pytorch:22.04-py3
LABEL authors="leedg17"
LABEL email="angry07@naver.com"

#RUN apt update  \
#    && apt install -y vim python3 python3-pip

## ubuntu
RUN addgroup appgroup && adduser appuser && adduser appuser appgroup
### alpine
##RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /home/appuser
#RUN pip3 install torch torchvision torchaudio

ENTRYPOINT ["watch", "-n", "10", "nvidia-smi"]
