# support tools (function calling)
langchain4j:
    ollama:
        embedding-model:
            base-url: http://172.27.6.8:11435
            model-name: llama3.2
            log-requests: true
            log-responses: true
            timeout: 600000
        chat-model:
            base-url: http://172.27.6.8:11435
            model-name: llama3.2
            log-requests: true
            log-responses: true
            timeout: 600000
        streaming-chat-model:
            base-url: http://172.27.6.8:11435
            model-name: llama3.2
            log-requests: true
            log-responses: true
            timeout: 600000