# Not support tool(function calling)
langchain4j:
    ollama:
        embedding-model:
            base-url: http://172.27.6.8:11435
            model-name: hf.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct-GGUF:Q8_0
            log-requests: true
            log-responses: true
            timeout: 600000
        chat-model:
            base-url: http://172.27.6.8:11435
            model-name: hf.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct-GGUF:Q8_0
            log-requests: true
            log-responses: true
            timeout: 600000
        streaming-chat-model:
            base-url: http://172.27.6.8:11435
            model-name: hf.co/LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct-GGUF:Q8_0
            log-requests: true
            log-responses: true
            timeout: 600000