logging:
    level:
        root: info
        dev.langchain4j: debug
        dev.langchain4j.model.ollama.OllamaClient: info
        dev.ai4j.openai4j: info
        com.example.chatbot: debug
        com.vaadin : info

spring:
    profiles:
        active: exaone
    application:
        name: chatbot
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:chatbotDisk;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=3000
        username: sa
        password: sa
        hikari:
            pool-name: disk-pool
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: false
            path: /h2-console
    threads:
        virtual:
            enabled: true
    data:
        redis:
            host: 172.27.6.8
            port: 7379
        redis-stack:
            host: 172.27.6.8
            port: 8379

application:
    pdf: src/test/resources/pdf

vaadin:
    exclude-urls: /swagger-ui.html,/swagger-ui/**
