#https://github.com/ollama/ollama/blob/main/docs/import.md#importing-a-model-from-safetensors-weights
FROM ollama/ollama:latest
LABEL authors="leedg17"

RUN apt update  \
    && apt install -y vim

## ubuntu
RUN addgroup appgroup && adduser appuser && adduser appuser appgroup
### alpine
##RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

WORKDIR /home/appuser
RUN mkdir -p safetensors/dongjin-kr_ko-reranker
COPY ollama-model/safetensors/dongjin-kr_ko-reranker safetensors/dongjin-kr_ko-reranker
